version: '3.9'

services:
  csw-database:
    container_name: csw-database
    image: postgres:14.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csw-database

  # csw-backend:
  #   container_name: csw-backend
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - csw-database
  #   links:
  #     - csw-database
